// Code generated by go generate; DO NOT EDIT.

package criterion

import "encoding/json"

type ConstraintLevel string

const (
	ConstraintLevelHard ConstraintLevel = "hard"
	ConstraintLevelSoft ConstraintLevel = "soft"
)

type ConstraintCategory string

const (
	ConstraintCategoryFormat   ConstraintCategory = "format"
	ConstraintCategoryContent  ConstraintCategory = "content"
	ConstraintCategoryStyle    ConstraintCategory = "style"
	ConstraintCategoryTool     ConstraintCategory = "tool"
	ConstraintCategoryState    ConstraintCategory = "state"
	ConstraintCategorySecurity ConstraintCategory = "security"
	ConstraintCategorySemantic ConstraintCategory = "semantic"
)

type RepairStrategy string

const (
	RepairStrategyPatch            RepairStrategy = "patch"
	RepairStrategyInsertSection    RepairStrategy = "insert_section"
	RepairStrategyRegenerateRegion RepairStrategy = "regenerate_region"
	RepairStrategyFull             RepairStrategy = "full"
)

type ConstraintRepair struct {
	MaxRounds    int            `json:"max_rounds,omitempty"`
	Strategy     RepairStrategy `json:"strategy"`
	TargetRegion string         `json:"target_region,omitempty"`
}

type ConstraintIR struct {
	Arg          json.RawMessage    `json:"arg,omitempty"`
	Category     ConstraintCategory `json:"category"`
	Description  string             `json:"description"`
	ID           string             `json:"id"`
	Level        ConstraintLevel    `json:"level"`
	Path         string             `json:"path,omitempty"`
	Priority     float64            `json:"priority"`
	Repair       *ConstraintRepair  `json:"repair,omitempty"`
	VerifyMethod string             `json:"verify_method"`
}
