// Code generated by go generate; DO NOT EDIT.

package criterion

type DetectedAt string

const (
	DetectedAtPreDecode    DetectedAt = "pre_decode"
	DetectedAtPostDecode   DetectedAt = "post_decode"
	DetectedAtPostToolCall DetectedAt = "post_tool_call"
)

type EvidenceSpan struct {
	CharRange   []int  `json:"char_range,omitempty"`
	JSONPointer string `json:"json_pointer,omitempty"`
	LineRange   []int  `json:"line_range,omitempty"`
	RegionID    string `json:"region_id,omitempty"`
}

type ConstraintViolation struct {
	Category     ConstraintCategory `json:"category"`
	ConstraintID string             `json:"constraint_id"`
	DetectedAt   DetectedAt         `json:"detected_at"`
	EvidenceSpan *EvidenceSpan      `json:"evidence_span,omitempty"`
	Hint         string             `json:"hint"`
	Level        ConstraintLevel    `json:"level"`
}
